export const enum StateEnum {
  EOF = -1,
  DATA = 1,
  RCDATA,
  RAWTEXT,
  SCRIPT_DATA,
  PLAINTEXT,
  TAG_OPEN,
  END_TAG_OPEN,
  TAG_NAME,
  RCDATA_LESS_THAN_SIGN,
  RCDATA_END_TAG_OPEN,
  RCDATA_END_TAG_NAME,
  RCDATA_END_TAG_NAME_MATCHED,
  RAWTEXT_LESS_THAN_SIGN,
  RAWTEXT_END_TAG_OPEN,
  RAWTEXT_END_TAG_NAME,
  RAWTEXT_END_TAG_NAME_MATCHED,
  SCRIPT_DATA_LESS_THAN_SIGN,
  SCRIPT_DATA_END_TAG_OPEN,
  SCRIPT_DATA_END_TAG_NAME,
  SCRIPT_DATA_END_TAG_NAME_MATCHED,
  SCRIPT_DATA_ESCAPE_START,
  SCRIPT_DATA_ESCAPE_START_DASH,
  SCRIPT_DATA_ESCAPED,
  SCRIPT_DATA_ESCAPED_DASH,
  SCRIPT_DATA_ESCAPED_DASH_DASH,
  SCRIPT_DATA_ESCAPED_LESS_THAN_SIGN,
  SCRIPT_DATA_ESCAPED_END_TAG_OPEN,
  SCRIPT_DATA_ESCAPED_END_TAG_NAME,
  SCRIPT_DATA_DOUBLE_ESCAPE_START,
  SCRIPT_DATA_DOUBLE_ESCAPE_START_MATCHED,
  SCRIPT_DATA_DOUBLE_ESCAPED,
  SCRIPT_DATA_DOUBLE_ESCAPED_DASH,
  SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH,
  SCRIPT_DATA_DOUBLE_ESCAPED_LESS_THAN_SIGN,
  SCRIPT_DATA_DOUBLE_ESCAPE_END,
  SCRIPT_DATA_DOUBLE_ESCAPE_END_MATCHED,
  BEFORE_ATTRIBUTE_NAME,
  ATTRIBUTE_NAME,
  AFTER_ATTRIBUTE_NAME,
  BEFORE_ATTRIBUTE_VALUE,
  ATTRIBUTE_VALUE_DOUBLE_QUOTED,
  ATTRIBUTE_VALUE_SINGLE_QUOTED,
  ATTRIBUTE_VALUE_UNQUOTED,
  AFTER_ATTRIBUTE_VALUE_QUOTED,
  SELF_CLOSING_START_TAG,
  BOGUS_COMMENT,
  MARKUP_DECLARATION_OPEN,
  MARKUP_DECLARATION_FAIL,
  COMMENT_START,
  COMMENT_START_DASH,
  COMMENT,
  COMMENT_LESS_THAN_SIGN,
  COMMENT_LESS_THAN_SIGN_BANG,
  COMMENT_LESS_THAN_SIGN_BANG_DASH,
  COMMENT_LESS_THAN_SIGN_BANG_DASH_DASH,
  COMMENT_END_DASH,
  COMMENT_END,
  COMMENT_END_BANG,
  DOCTYPE,
  BEFORE_DOCTYPE_NAME,
  DOCTYPE_NAME,
  AFTER_DOCTYPE_NAME,
  AFTER_DOCTYPE_NAME_FAILED_SEQUENCE,
  AFTER_DOCTYPE_PUBLIC_KEYWORD,
  BEFORE_DOCTYPE_PUBLIC_IDENTIFIER,
  DOCTYPE_PUBLIC_IDENTIFIER_DOUBLE_QUOTED,
  DOCTYPE_PUBLIC_IDENTIFIER_SINGLE_QUOTED,
  AFTER_DOCTYPE_PUBLIC_IDENTIFIER,
  BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS,
  AFTER_DOCTYPE_SYSTEM_KEYWORD,
  BEFORE_DOCTYPE_SYSTEM_IDENTIFIER,
  DOCTYPE_SYSTEM_IDENTIFIER_DOUBLE_QUOTED,
  DOCTYPE_SYSTEM_IDENTIFIER_SINGLE_QUOTED,
  AFTER_DOCTYPE_SYSTEM_IDENTIFIER,
  BOGUS_DOCTYPE,
  CDATA_SECTION_START,
  CDATA_SECTION,
  CDATA_SECTION_BRACKET,
  CDATA_SECTION_END,
  CHARACTER_REFERENCE,
  NAMED_CHARACTER_REFERENCE,
  AMBIGUOUS_AMPERSAND,
  NUMERIC_CHARACTER_REFERENCE,
  HEXADECIMAL_CHARACTER_REFERENCE_START,
  DECIMAL_CHARACTER_REFERENCE_START,
  HEXADECIMAL_CHARACTER_REFERENCE,
  DECIMAL_CHARACTER_REFERENCE,
  SEQUENCE
}

export enum StateStringEnum {
  EOF = 'eof',
  DATA = 'data',
  RCDATA = 'rcdata',
  RAWTEXT = 'rawtext',
  SCRIPT_DATA = 'scriptData',
  PLAINTEXT = 'plaintext',
  TAG_OPEN = 'tagOpen',
  END_TAG_OPEN = 'endTagOpen',
  TAG_NAME = 'tagName',
  RCDATA_LESS_THAN_SIGN = 'rcdataLessThanSign',
  RCDATA_END_TAG_OPEN = 'rcdataEndTagOpen',
  RCDATA_END_TAG_NAME = 'rcdataEndTagName',
  RCDATA_END_TAG_NAME_MATCHED = 'rcdataEndTagNameMatched',
  RAWTEXT_LESS_THAN_SIGN = 'rawtextLessThanSign',
  RAWTEXT_END_TAG_OPEN = 'rawtextEndTagOpen',
  RAWTEXT_END_TAG_NAME = 'rawtextEndTagName',
  RAWTEXT_END_TAG_NAME_MATCHED = 'rawtextEndTagNameMatched',
  SCRIPT_DATA_LESS_THAN_SIGN = 'scriptDataLessThanSign',
  SCRIPT_DATA_END_TAG_OPEN = 'scriptDataEndTagOpen',
  SCRIPT_DATA_END_TAG_NAME = 'scriptDataEndTagName',
  SCRIPT_DATA_END_TAG_NAME_MATCHED = 'scriptDataEndTagNameMatched',
  SCRIPT_DATA_ESCAPE_START = 'scriptDataEscapeStart',
  SCRIPT_DATA_ESCAPE_START_DASH = 'scriptDataEscapeStartDash',
  SCRIPT_DATA_ESCAPED = 'scriptDataEscaped',
  SCRIPT_DATA_ESCAPED_DASH = 'scriptDataEscapedDash',
  SCRIPT_DATA_ESCAPED_DASH_DASH = 'scriptDataEscapedDashDash',
  SCRIPT_DATA_ESCAPED_LESS_THAN_SIGN = 'scriptDataEscapedLessThanSign',
  SCRIPT_DATA_ESCAPED_END_TAG_OPEN = 'scriptDataEscapedEndTagOpen',
  SCRIPT_DATA_ESCAPED_END_TAG_NAME = 'scriptDataEscapedEndTagName',
  SCRIPT_DATA_DOUBLE_ESCAPE_START = 'scriptDataDoubleEscapeStart',
  SCRIPT_DATA_DOUBLE_ESCAPE_START_MATCHED = 'scriptDataDoubleEscapeStartMatched',
  SCRIPT_DATA_DOUBLE_ESCAPED = 'scriptDataDoubleEscaped',
  SCRIPT_DATA_DOUBLE_ESCAPED_DASH = 'scriptDataDoubleEscapedDash',
  SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH = 'scriptDataDoubleEscapedDashDash',
  SCRIPT_DATA_DOUBLE_ESCAPED_LESS_THAN_SIGN = 'scriptDataDoubleEscapedLessThanSign',
  SCRIPT_DATA_DOUBLE_ESCAPE_END = 'scriptDataDoubleEscapeEnd',
  SCRIPT_DATA_DOUBLE_ESCAPE_END_MATCHED = 'scriptDataDoubleEscapeEndMatched',
  BEFORE_ATTRIBUTE_NAME = 'beforeAttributeName',
  ATTRIBUTE_NAME = 'attributeName',
  AFTER_ATTRIBUTE_NAME = 'afterAttributeName',
  BEFORE_ATTRIBUTE_VALUE = 'beforeAttributeValue',
  ATTRIBUTE_VALUE_DOUBLE_QUOTED = 'attributeValueDoubleQuoted',
  ATTRIBUTE_VALUE_SINGLE_QUOTED = 'attributeValueSingleQuoted',
  ATTRIBUTE_VALUE_UNQUOTED = 'attributeValueUnquoted',
  AFTER_ATTRIBUTE_VALUE_QUOTED = 'afterAttributeValueQuoted',
  SELF_CLOSING_START_TAG = 'selfClosingStartTag',
  BOGUS_COMMENT = 'bogusComment',
  MARKUP_DECLARATION_OPEN = 'markupDeclarationOpen',
  MARKUP_DECLARATION_FAIL = 'markupDeclarationFail',
  COMMENT_START = 'commentStart',
  COMMENT_START_DASH = 'commentStartDash',
  COMMENT = 'comment',
  COMMENT_LESS_THAN_SIGN = 'commentLessThanSign',
  COMMENT_LESS_THAN_SIGN_BANG = 'commentLessThanSignBang',
  COMMENT_LESS_THAN_SIGN_BANG_DASH = 'commentLessThanSignBangDash',
  COMMENT_LESS_THAN_SIGN_BANG_DASH_DASH = 'commentLessThanSignBangDashDash',
  COMMENT_END_DASH = 'commentEndDash',
  COMMENT_END = 'commentEnd',
  COMMENT_END_BANG = 'commentEndBang',
  DOCTYPE = 'doctype',
  BEFORE_DOCTYPE_NAME = 'beforeDoctypeName',
  DOCTYPE_NAME = 'doctypeName',
  AFTER_DOCTYPE_NAME = 'afterDoctypeName',
  AFTER_DOCTYPE_NAME_FAILED_SEQUENCE = 'afterDoctypeNameFailedSequence',
  AFTER_DOCTYPE_PUBLIC_KEYWORD = 'afterDoctypePublicKeyword',
  BEFORE_DOCTYPE_PUBLIC_IDENTIFIER = 'beforeDoctypePublicIdentifier',
  DOCTYPE_PUBLIC_IDENTIFIER_DOUBLE_QUOTED = 'doctypePublicIdentifierDoubleQuoted',
  DOCTYPE_PUBLIC_IDENTIFIER_SINGLE_QUOTED = 'doctypePublicIdentifierSingleQuoted',
  AFTER_DOCTYPE_PUBLIC_IDENTIFIER = 'afterDoctypePublicIdentifier',
  BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS = 'betweenDoctypePublicAndSystemIdentifiers',
  AFTER_DOCTYPE_SYSTEM_KEYWORD = 'afterDoctypeSystemKeyword',
  BEFORE_DOCTYPE_SYSTEM_IDENTIFIER = 'beforeDoctypeSystemIdentifier',
  DOCTYPE_SYSTEM_IDENTIFIER_DOUBLE_QUOTED = 'doctypeSystemIdentifierDoubleQuoted',
  DOCTYPE_SYSTEM_IDENTIFIER_SINGLE_QUOTED = 'doctypeSystemIdentifierSingleQuoted',
  AFTER_DOCTYPE_SYSTEM_IDENTIFIER = 'afterDoctypeSystemIdentifier',
  BOGUS_DOCTYPE = 'bogusDoctype',
  CDATA_SECTION_START = 'cdataSectionStart',
  CDATA_SECTION = 'cdataSection',
  CDATA_SECTION_BRACKET = 'cdataSectionBracket',
  CDATA_SECTION_END = 'cdataSectionEnd',
  CHARACTER_REFERENCE = 'characterReference',
  NAMED_CHARACTER_REFERENCE = 'namedCharacterReference',
  AMBIGUOUS_AMPERSAND = 'ambiguousAmpersand',
  NUMERIC_CHARACTER_REFERENCE = 'numericCharacterReference',
  HEXADECIMAL_CHARACTER_REFERENCE_START = 'hexadecimalCharacterReferenceStart',
  DECIMAL_CHARACTER_REFERENCE_START = 'decimalCharacterReferenceStart',
  HEXADECIMAL_CHARACTER_REFERENCE = 'hexadecimalCharacterReference',
  DECIMAL_CHARACTER_REFERENCE = 'decimalCharacterReference',
  SEQUENCE = 'sequence'
}

export enum StateStringReversedEnum {
  eof = StateEnum.EOF,
  data = StateEnum.DATA,
  rcdata = StateEnum.RCDATA,
  rawtext = StateEnum.RAWTEXT,
  scriptData = StateEnum.SCRIPT_DATA,
  plaintext = StateEnum.PLAINTEXT,
  tagOpen = StateEnum.TAG_OPEN,
  endTagOpen = StateEnum.END_TAG_OPEN,
  tagName = StateEnum.TAG_NAME,
  rcdataLessThanSign = StateEnum.RCDATA_LESS_THAN_SIGN,
  rcdataEndTagOpen = StateEnum.RCDATA_END_TAG_OPEN,
  rcdataEndTagName = StateEnum.RCDATA_END_TAG_NAME,
  rcdataEndTagNameMatched = StateEnum.RCDATA_END_TAG_NAME_MATCHED,
  rawtextLessThanSign = StateEnum.RAWTEXT_LESS_THAN_SIGN,
  rawtextEndTagOpen = StateEnum.RAWTEXT_END_TAG_OPEN,
  rawtextEndTagName = StateEnum.RAWTEXT_END_TAG_NAME,
  rawtextEndTagNameMatched = StateEnum.RAWTEXT_END_TAG_NAME_MATCHED,
  scriptDataLessThanSign = StateEnum.SCRIPT_DATA_LESS_THAN_SIGN,
  scriptDataEndTagOpen = StateEnum.SCRIPT_DATA_END_TAG_OPEN,
  scriptDataEndTagName = StateEnum.SCRIPT_DATA_END_TAG_NAME,
  scriptDataEndTagNameMatched = StateEnum.SCRIPT_DATA_END_TAG_NAME_MATCHED,
  scriptDataEscapeStart = StateEnum.SCRIPT_DATA_ESCAPE_START,
  scriptDataEscapeStartDash = StateEnum.SCRIPT_DATA_ESCAPE_START_DASH,
  scriptDataEscaped = StateEnum.SCRIPT_DATA_ESCAPED,
  scriptDataEscapedDash = StateEnum.SCRIPT_DATA_ESCAPED_DASH,
  scriptDataEscapedDashDash = StateEnum.SCRIPT_DATA_ESCAPED_DASH_DASH,
  scriptDataEscapedLessThanSign = StateEnum.SCRIPT_DATA_ESCAPED_LESS_THAN_SIGN,
  scriptDataEscapedEndTagOpen = StateEnum.SCRIPT_DATA_ESCAPED_END_TAG_OPEN,
  scriptDataEscapedEndTagName = StateEnum.SCRIPT_DATA_ESCAPED_END_TAG_NAME,
  scriptDataDoubleEscapeStart = StateEnum.SCRIPT_DATA_DOUBLE_ESCAPE_START,
  scriptDataDoubleEscapeStartMatched = StateEnum.SCRIPT_DATA_DOUBLE_ESCAPE_START_MATCHED,
  scriptDataDoubleEscaped = StateEnum.SCRIPT_DATA_DOUBLE_ESCAPED,
  scriptDataDoubleEscapedDash = StateEnum.SCRIPT_DATA_DOUBLE_ESCAPED_DASH,
  scriptDataDoubleEscapedDashDash = StateEnum.SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH,
  scriptDataDoubleEscapedLessThanSign = StateEnum.SCRIPT_DATA_DOUBLE_ESCAPED_LESS_THAN_SIGN,
  scriptDataDoubleEscapeEnd = StateEnum.SCRIPT_DATA_DOUBLE_ESCAPE_END,
  scriptDataDoubleEscapeEndMatched = StateEnum.SCRIPT_DATA_DOUBLE_ESCAPE_END_MATCHED,
  beforeAttributeName = StateEnum.BEFORE_ATTRIBUTE_NAME,
  attributeName = StateEnum.ATTRIBUTE_NAME,
  afterAttributeName = StateEnum.AFTER_ATTRIBUTE_NAME,
  beforeAttributeValue = StateEnum.BEFORE_ATTRIBUTE_VALUE,
  attributeValueDoubleQuoted = StateEnum.ATTRIBUTE_VALUE_DOUBLE_QUOTED,
  attributeValueSingleQuoted = StateEnum.ATTRIBUTE_VALUE_SINGLE_QUOTED,
  attributeValueUnquoted = StateEnum.ATTRIBUTE_VALUE_UNQUOTED,
  afterAttributeValueQuoted = StateEnum.AFTER_ATTRIBUTE_VALUE_QUOTED,
  selfClosingStartTag = StateEnum.SELF_CLOSING_START_TAG,
  bogusComment = StateEnum.BOGUS_COMMENT,
  markupDeclarationOpen = StateEnum.MARKUP_DECLARATION_OPEN,
  markupDeclarationFail = StateEnum.MARKUP_DECLARATION_FAIL,
  commentStart = StateEnum.COMMENT_START,
  commentStartDash = StateEnum.COMMENT_START_DASH,
  comment = StateEnum.COMMENT,
  commentLessThanSign = StateEnum.COMMENT_LESS_THAN_SIGN,
  commentLessThanSignBang = StateEnum.COMMENT_LESS_THAN_SIGN_BANG,
  commentLessThanSignBangDash = StateEnum.COMMENT_LESS_THAN_SIGN_BANG_DASH,
  commentLessThanSignBangDashDash = StateEnum.COMMENT_LESS_THAN_SIGN_BANG_DASH_DASH,
  commentEndDash = StateEnum.COMMENT_END_DASH,
  commentEnd = StateEnum.COMMENT_END,
  commentEndBang = StateEnum.COMMENT_END_BANG,
  doctype = StateEnum.DOCTYPE,
  beforeDoctypeName = StateEnum.BEFORE_DOCTYPE_NAME,
  doctypeName = StateEnum.DOCTYPE_NAME,
  afterDoctypeName = StateEnum.AFTER_DOCTYPE_NAME,
  afterDoctypeNameFailedSequence = StateEnum.AFTER_DOCTYPE_NAME_FAILED_SEQUENCE,
  afterDoctypePublicKeyword = StateEnum.AFTER_DOCTYPE_PUBLIC_KEYWORD,
  beforeDoctypePublicIdentifier = StateEnum.BEFORE_DOCTYPE_PUBLIC_IDENTIFIER,
  doctypePublicIdentifierDoubleQuoted = StateEnum.DOCTYPE_PUBLIC_IDENTIFIER_DOUBLE_QUOTED,
  doctypePublicIdentifierSingleQuoted = StateEnum.DOCTYPE_PUBLIC_IDENTIFIER_SINGLE_QUOTED,
  afterDoctypePublicIdentifier = StateEnum.AFTER_DOCTYPE_PUBLIC_IDENTIFIER,
  betweenDoctypePublicAndSystemIdentifiers = StateEnum.BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS,
  afterDoctypeSystemKeyword = StateEnum.AFTER_DOCTYPE_SYSTEM_KEYWORD,
  beforeDoctypeSystemIdentifier = StateEnum.BEFORE_DOCTYPE_SYSTEM_IDENTIFIER,
  doctypeSystemIdentifierDoubleQuoted = StateEnum.DOCTYPE_SYSTEM_IDENTIFIER_DOUBLE_QUOTED,
  doctypeSystemIdentifierSingleQuoted = StateEnum.DOCTYPE_SYSTEM_IDENTIFIER_SINGLE_QUOTED,
  afterDoctypeSystemIdentifier = StateEnum.AFTER_DOCTYPE_SYSTEM_IDENTIFIER,
  bogusDoctype = StateEnum.BOGUS_DOCTYPE,
  cdataSectionStart = StateEnum.CDATA_SECTION_START,
  cdataSection = StateEnum.CDATA_SECTION,
  cdataSectionBracket = StateEnum.CDATA_SECTION_BRACKET,
  cdataSectionEnd = StateEnum.CDATA_SECTION_END,
  characterReference = StateEnum.CHARACTER_REFERENCE,
  namedCharacterReference = StateEnum.NAMED_CHARACTER_REFERENCE,
  ambiguousAmpersand = StateEnum.AMBIGUOUS_AMPERSAND,
  numericCharacterReference = StateEnum.NUMERIC_CHARACTER_REFERENCE,
  hexadecimalCharacterReferenceStart = StateEnum.HEXADECIMAL_CHARACTER_REFERENCE_START,
  decimalCharacterReferenceStart = StateEnum.DECIMAL_CHARACTER_REFERENCE_START,
  hexadecimalCharacterReference = StateEnum.HEXADECIMAL_CHARACTER_REFERENCE,
  decimalCharacterReference = StateEnum.DECIMAL_CHARACTER_REFERENCE,
  sequence = StateEnum.SEQUENCE
}