export type State =
    'data' |
    'rcdata' |
    'rawtext' |
    'scriptData' |
    'plaintext' |
    'tagOpen' |
    'endTagOpen' |
    'tagName' |
    'rcdataLessThanSign' |
    'rcdataEndTagOpen' |
    'rcdataEndTagName' |
    'rcdataEndTagNameMatched' |
    'rawtextLessThanSign' |
    'rawtextEndTagOpen' |
    'rawtextEndTagName' |
    'rawtextEndTagNameMatched' |
    'scriptDataLessThanSign' |
    'scriptDataEndTagOpen' |
    'scriptDataEndTagName' |
    'scriptDataEndTagNameMatched' |
    'scriptDataEscapeStart' |
    'scriptDataEscapeStartDash' |
    'scriptDataEscaped' |
    'scriptDataEscapedDash' |
    'scriptDataEscapedDashDash' |
    'scriptDataEscapedLessThanSign' |
    'scriptDataEscapedEndTagOpen' |
    'scriptDataEscapedEndTagName' |
    'scriptDataEscapedEndTagNameMatched' |
    'scriptDataDoubleEscapeStart' |
    'scriptDataDoubleEscapeStartMatched' |
    'scriptDataDoubleEscaped' |
    'scriptDataDoubleEscapedDash' |
    'scriptDataDoubleEscapedDashDash' |
    'scriptDataDoubleEscapedLessThanSign' |
    'scriptDataDoubleEscapeEnd' |
    'scriptDataDoubleEscapeEndMatched' |
    'beforeAttributeName' |
    'attributeName' |
    'afterAttributeName' |
    'beforeAttributeValue' |
    'attributeValueDoubleQuoted' |
    'attributeValueSingleQuoted' |
    'attributeValueUnquoted' |
    'afterAttributeValueQuoted' |
    'selfClosingStartTag' |
    'bogusComment' |
    'markupDeclarationOpen' |
    'markupDeclarationFail' |
    'commentStart' |
    'commentStartDash' |
    'comment' |
    'commentLessThanSign' |
    'commentLessThanSignBang' |
    'commentLessThanSignBangDash' |
    'commentLessThanSignBangDashDash' |
    'commentEndDash' |
    'commentEnd' |
    'commentEndBang' |
    'doctype' |
    'beforeDoctypeName' |
    'doctypeName' |
    'afterDoctypeName' |
    'afterDoctypeNameFailedSequence' |
    'afterDoctypePublicKeyword' |
    'beforeDoctypePublicIdentifier' |
    'doctypePublicIdentifierDoubleQuoted' |
    'doctypePublicIdentifierSingleQuoted' |
    'afterDoctypePublicIdentifier' |
    'betweenDoctypePublicAndSystemIdentifiers' |
    'afterDoctypeSystemKeyword' |
    'beforeDoctypeSystemIdentifier' |
    'doctypeSystemIdentifierDoubleQuoted' |
    'doctypeSystemIdentifierSingleQuoted' |
    'afterDoctypeSystemIdentifier' |
    'bogusDoctype' |
    'cdataSectionStart' |
    'cdataSection' |
    'cdataSectionBracket' |
    'cdataSectionEnd' |
    'characterReference' |
    'namedCharacterReference' |
    'ambiguousAmpersand' |
    'numericCharacterReference' |
    'hexadecimalCharacterReferenceStart' |
    'decimalCharacterReferenceStart' |
    'hexadecimalCharacterReference' |
    'decimalCharacterReference' |
    'eof' |
    'eoc' |
    'sequence';
